const FILMES = [
  {
    id: "de-volta-ao-lar",
    titulo: "Homem-Aranha: De Volta ao Lar",
    ano: 2017,
    poster: "assets/capas/de-volta-ao-lar.jpg",
    nota: "Primeira aparição de Peter Parker como protagonista no Universo Cinematográfico Marvel, sob a orientação de Tony Stark.",
  },
  {
    id: "guerra-infinita",
    titulo: "Vingadores: Guerra Infinita",
    ano: 2018,
    poster: "assets/capas/guerra-infinita.jpg",
    nota: "Peter Parker recebe o Traje Aranha de Ferro e se junta aos Vingadores no confronto contra Thanos.",
  },
  {
    id: "ultimato",
    titulo: "Vingadores: Ultimato",
    ano: 2019,
    poster: "assets/capas/ultimato.webp",
    nota: "Desfecho da saga do Infinito, com o retorno de Peter Parker à batalha final contra Thanos.",
  },
  {
    id: "longe-de-casa",
    titulo: "Homem-Aranha: Longe de Casa",
    ano: 2019,
    poster: "assets/capas/longe-de-casa.jpg",
    nota: "Peter Parker enfrenta Mysterio durante uma viagem escolar pela Europa, tentando equilibrar a vida de herói e estudante.",
  },
  {
    id: "sem-volta-pra-casa",
    titulo: "Homem-Aranha: Sem Volta Pra Casa",
    ano: 2021,
    poster: "assets/capas/sem-volta-pra-casa.jpg",
    nota: "Um feitiço malsucedido rompe o multiverso, trazendo vilões de outras realidades para enfrentar Peter Parker.",
  },
];

const TRAJES = [
  {
    id: "homecoming",
    nome: "Traje Homecoming",
    filme: "Homem-Aranha: De Volta ao Lar",
    ano: "2017",
    imagem: "assets/trajes/traje-homecoming.png",
    nota: "Primeiro traje avançado entregue por Tony Stark a Peter Parker, equipado com recursos tecnológicos da Stark Industries.",
  },
  {
    id: "aranha-de-ferro",
    nome: "Traje Aranha de Ferro",
    filme: "Vingadores: Guerra Infinita e Vingadores: Ultimato",
    ano: "2018 e 2019",
    imagem: "assets/trajes/traje-aranha-de-ferro.png",
    nota: "Equipamento com pernas mecânicas retráteis, projetado por Tony Stark para o combate direto ao lado dos Vingadores.",
  },
  {
    id: "furtivo",
    nome: "Traje Furtivo",
    filme: "Homem-Aranha: Longe de Casa",
    ano: "2019",
    imagem: "assets/trajes/traje-furtivo.png",
    nota: "Uniforme discreto de operações táticas, cedido por Nick Fury durante a viagem escolar pela Europa.",
  },
  {
    id: "aprimorado",
    nome: "Traje Aprimorado",
    filme: "Homem-Aranha: Longe de Casa",
    ano: "2019",
    imagem: "assets/trajes/traje-aprimorado.png",
    nota: "Versão em vermelho e preto apresentada por Peter Parker como o primeiro uniforme de sua própria concepção.",
  },
  {
    id: "integrado",
    nome: "Traje Integrado",
    filme: "Homem-Aranha: Longe de Casa",
    ano: "2019",
    imagem: "assets/trajes/traje-integrado.png",
    nota: "Versão final do traje, utilizada no confronto decisivo contra Mysterio nas ruas de Londres.",
  },
];

const VILOES = [
  {
    id: "abutre",
    nome: "Abutre",
    identidade: "Adrian Toomes",
    ator: "Michael Keaton",
    filme: "Homem-Aranha: De Volta ao Lar",
    ano: "2017",
    imagem: "assets/viloes/abutre.png",
    nota: "Ex-contratante de limpeza de destroços alienígenas que se voltou ao contrabando de tecnologia após perder o próprio negócio.",
  },
  {
    id: "dr-octopus",
    nome: "Doutor Octopus",
    identidade: "Otto Octavius",
    ator: "Alfred Molina",
    filme: "Homem-Aranha: Sem Volta Pra Casa",
    ano: "2021",
    imagem: "assets/viloes/dr-octopus.png",
    nota: "Cientista cujos braços mecânicos assumiram controle sobre sua mente, trazido de outra realidade por uma fenda multiversal.",
  },
  {
    id: "lagarto",
    nome: "Lagarto",
    identidade: "Dr. Curt Connors",
    ator: "Rhys Ifans",
    filme: "Homem-Aranha: Sem Volta Pra Casa",
    ano: "2021",
    imagem: "assets/viloes/lagarto.png",
    nota: "Pesquisador transformado após um experimento próprio com regeneração celular, também originário de outra realidade.",
  },
  {
    id: "homem-areia",
    nome: "Homem-Areia",
    identidade: "Flint Marko",
    ator: "Thomas Haden Church",
    filme: "Homem-Aranha: Sem Volta Pra Casa",
    ano: "2021",
    imagem: "assets/viloes/homem-areia.png",
    nota: "Fugitivo com o corpo transformado em areia manipulável após um acidente com um acelerador de partículas.",
  },
  {
    id: "mysterio",
    nome: "Mysterio",
    identidade: "Quentin Beck",
    ator: "Jake Gyllenhaal",
    filme: "Homem-Aranha: Longe de Casa",
    ano: "2019",
    imagem: "assets/viloes/mysterio.png",
    nota: "Ex-funcionário da Stark Industries que forjou uma identidade heroica utilizando ilusões e uma frota de drones.",
  },
];
